name: 🐧 Build Linux Kernel
on:
  push:
    paths:
      - "kernel/*"
      - "**.conf"
      - "**.yml"
jobs:
  BuildKernel:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
      - run: echo "💡 The ${{ github.repository }} repository has been cloned."
      - name: Running build.sh
        run: cd kernel; bash build.sh chromeos-5.10;
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: assets-for-download
          path: |
            kernel/bzImage
            kernel/modules*